extends Area2D


# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	$AnimationPlayer.play("rotate")

func _physics_process(delta: float) -> void:
	if $"/root/Global".gamerunning:
		global_position.x -= $"/root/Global".speed*delta
	

func _on_body_entered(body: Node2D) -> void:
	if body.name == "Duck":
		#print("duck touched")
		$AnimationPlayer.play("explode")
		#await await $AnimationPlayer.animation_finished
		##queue_free()
		#print("animation finisched")
		# add coin
	if body.name == "hurdle":
		pass#queue_free()
